import * as crypto from 'node:crypto';
import type { Message, Session } from '../types.js';

/**
 * SessionStore — session CRUD abstraction consumed by the WebUI server
 * (PLAN Task 17) and later the in-process harness integration (Task 19).
 * The WebUI backend depends on this interface via dependency injection, never
 * on a global singleton.
 */
export interface SessionStore {
  /**
   * Create a session in `running` state with the given task.
   * @param maxRounds 0 = unlimited; undefined = the store's default cap.
   * @param workspaceRoot session workspace root; undefined = the store's
   *   default (config agent.workspaceRoot in the integrated harness).
   */
  create(task: string, maxRounds?: number, workspaceRoot?: string): Session;
  /** All sessions, oldest first. */
  list(): Session[];
  /** Session by id, or null when unknown. */
  get(id: string): Session | null;
  /** Transition the session status; returns the updated session or null. */
  updateStatus(id: string, status: Session['status']): Session | null;
  /**
   * Append a message (id + timestamp generated by the store) and return the
   * stored message, or null when the session is unknown.
   */
  appendMessage(id: string, message: Omit<Message, 'id' | 'timestamp'>): Message | null;
}

function generateId(): string {
  return crypto.randomUUID();
}

function nowISO(): string {
  return new Date().toISOString();
}

/** In-memory SessionStore used by the WebUI backend and its tests. */
export class InMemorySessionStore implements SessionStore {
  private readonly sessions = new Map<string, Session>();

  // Defaults mirror DEFAULT_CONFIG (maxRounds 0 = unlimited) — callers that
  // pass a config should always inject config.agent values explicitly.
  constructor(
    private readonly defaultMaxRounds: number = 0,
    private readonly defaultWorkspaceRoot: string = process.cwd(),
  ) {}

  create(task: string, maxRounds?: number, workspaceRoot?: string): Session {
    const now = nowISO();
    const session: Session = {
      id: generateId(),
      task,
      status: 'running',
      maxRounds: maxRounds ?? this.defaultMaxRounds,
      currentRound: 0,
      workspaceRoot: workspaceRoot ?? this.defaultWorkspaceRoot,
      messages: [],
      tokenCount: 0,
      createdAt: now,
      updatedAt: now,
    };
    this.sessions.set(session.id, session);
    return session;
  }

  list(): Session[] {
    return [...this.sessions.values()];
  }

  get(id: string): Session | null {
    return this.sessions.get(id) ?? null;
  }

  updateStatus(id: string, status: Session['status']): Session | null {
    const session = this.sessions.get(id);
    if (!session) {
      return null;
    }
    session.status = status;
    session.updatedAt = nowISO();
    return session;
  }

  appendMessage(id: string, message: Omit<Message, 'id' | 'timestamp'>): Message | null {
    const session = this.sessions.get(id);
    if (!session) {
      return null;
    }
    const stored: Message = { ...message, id: generateId(), timestamp: nowISO() };
    session.messages.push(stored);
    session.updatedAt = nowISO();
    return stored;
  }
}
